### ISSUE TITLE
set up a runit service 

### ISSUE THREAD

**Issue by jtimberman** [jtimberman/mosh-cookbook#1]
Start the mosh-server as a runit service enabled with init_style attribute.

**Comment by jtimberman** [comment]
This may or may not make sense based on the mosh-server behavior (terminates when client disconnects)

**Comment by andreacampi** [comment]
Yeah, when I read that I was: what? :)
Seriously, I don't think it's needed.

**Comment by jtimberman** [comment]
Nope, not going to do this.
