### ISSUE TITLE
Add name to metadata

### ISSUE THREAD

**Issue by chrisferry** [jtimberman/mosh-cookbook#15]
Ridley killing "vagrant up" as 'name' is missing from metadata.

Updating Vagrant's berkshelf: '/Users/chris.ferry/.berkshelf/default/vagrant/berkshelf-20140723-36097-1hbjli6-default'
Resolving cookbook dependencies...
Fetching 'mosh-cookbook' from https://github.com/jtimberman/mosh-cookbook.git (at master)
/Users/chris.ferry/.vagrant.d/gems/gems/ridley-4.0.0/lib/ridley/chef/cookbook.rb:44:in `from_path': The metadata at '/var/folders/11/d6g_dbdx7xb2yq7z1bjq2yfm45msx9/T/d20140723-37060-1bxyan2' does not contain a 'name' attribute. While Chef does not strictly enforce this requirement, Ridley cannot continue without a valid metadata 'name' entry. (Ridley::Errors::MissingNameAttribute)
    from /Users/chris.ferry/.vagrant.d/gems/gems/berkshelf-3.1.4/lib/berkshelf/locations/base.rb:62:in`validate_cached!'

**Comment by vitorbaptista** [comment]
This is fixed but the version on https://supermarket.chef.io/cookbooks/mosh wasn't updated in a long time (and doesn't include it). @jtimberman Could you release a new version?

**Comment by jtimberman** [comment]
Done, this is in 0.3.1. Thanks!
