### ISSUE TITLE
Source recipe raises error

### ISSUE THREAD

**Issue by whittle** [jtimberman/mosh-cookbook#4]
A node with a run list of `[recipe[getting-started], recipe[chef-client], recipe[aws], recipe[apt], recipe[mosh]]` with attribute `{"mosh": {"install_type": "source"}}` raises the error at https://gist.github.com/2363598.

**Comment by jtimberman** [comment]
This should be fixed in v0.2.0.

**Comment by whittle** [comment]
Thanks!
